compile_pdf:
  stage: build
  image: aergus/latex:latest  # use a Docker image for LaTeX from https://hub.docker.com/
  script: 
    - ls
    - latexmk -pdf main.tex  # build the pdf just as you would on your computer !
    - cd MIMAR2021
    - latexmk -pdf presentation-mimar-2021.tex
    - cd ..
  artifacts:
    paths: 
      - main.pdf  # instruct GitLab to keep the main.pdf file !
      - presentation-mimar-2021.pdf

pages:
  stage: test
  image: python:3.8.5-slim-buster
  script:
  - apt update && apt install -y -qq pandoc
  - mkdir html ; mv main.pdf html ; mv ./MIMAR2021/presentation-mimar-2021.pdf html
  - pandoc docs/index.md -t html -o html/index.html
  - mv html public/
  artifacts:
    paths:
    - public
